name: actionlint
on:
  push:
    branches: [main]
  pull_request:
    branches: ['**']
permissions: {}
jobs:
  actionlint:
    permissions:
      contents: read
    uses: rknightion/.github/.github/workflows/actionlint.yml@3b145adef40aecb043c24f80bfe44c95d57741a2 # v1.25.4
