name: actionlint
on:
  push:
    branches: [main]
  pull_request:
    branches: ['**']
permissions: {}
jobs:
  actionlint:
    permissions:
      contents: read
    uses: rknightion/.github/.github/workflows/actionlint.yml@c636bd20758433033cb4fe7760867b1318523bbb # v1.17.0
