name: Dependency review
on:
  pull_request:
    branches: [main]
permissions: {}
jobs:
  dependency-review:
    permissions:
      contents: read
      pull-requests: write
    uses: rknightion/.github/.github/workflows/dependency-review.yml@c36bf7ded21407b0a5169ecb2502d6a3a385be30 # v1.25.5
