name: Dependency review
on:
  pull_request:
    branches: [main]
permissions: {}
jobs:
  dependency-review:
    permissions:
      contents: read
      pull-requests: write
    uses: rknightion/.github/.github/workflows/dependency-review.yml@f32275a4a7641f34db5cb005d270db961b54a680 # v1.25.3
