name: Docker Security
on:
  push:
    branches: [main]
  schedule:
    - cron: '37 5 * * 2'
  workflow_dispatch:
permissions: {}
jobs:
  docker-security:
    permissions:
      contents: read
      security-events: write
    uses: rknightion/.github/.github/workflows/docker-security.yml@81fc55183265da0b21e92e690f70d679b20ed822 # v1.21.0
