name: Docker Security
on:
  push:
    branches: [main]
  schedule:
    - cron: '37 5 * * 2'
  workflow_dispatch:
permissions: {}
jobs:
  docker-security:
    permissions:
      contents: read
      security-events: write
    uses: rknightion/.github/.github/workflows/docker-security.yml@ff43f62eaec9f41d49b9a208d86b2eb932c97056 # v1.18.1
