name: Docker Security
on:
  push:
    branches: [main]
  schedule:
    - cron: '37 5 * * 2'
  workflow_dispatch:
permissions: {}
jobs:
  docker-security:
    permissions:
      contents: read
      security-events: write
    uses: rknightion/.github/.github/workflows/docker-security.yml@b3f1cef6e76ce206b01e1a3bae63ce115a1cf570 # v1.10.0
