name: Scorecard
on:
  push:
    branches: [main]
  schedule:
    - cron: '51 10 * * 6'
permissions: {}
jobs:
  scorecard:
    permissions:
      security-events: write
      id-token: write
    uses: rknightion/.github/.github/workflows/scorecard.yml@e17f6f1a010f50cf878b310cf90820f14c0bbbf6 # v1.25.2
