name: zizmor
on:
  push:
    branches: [main]
  pull_request:
    branches: ['**']
permissions: {}
jobs:
  zizmor:
    permissions:
      security-events: write
      contents: read
      actions: read
    uses: rknightion/.github/.github/workflows/zizmor.yml@e5fb83e8b9fac5d9bcca87c9f189ec3ea946de84 # v1.21.1
