name: zizmor
on:
  push:
    branches: [main]
  pull_request:
    branches: ['**']
permissions: {}
jobs:
  zizmor:
    permissions:
      security-events: write
      contents: read
      actions: read
    uses: rknightion/.github/.github/workflows/zizmor.yml@81fc55183265da0b21e92e690f70d679b20ed822 # v1.21.0
