name: zizmor
on:
  push:
    branches: [main]
  pull_request:
    branches: ['**']
permissions: {}
jobs:
  zizmor:
    permissions:
      security-events: write
      contents: read
      actions: read
    uses: rknightion/.github/.github/workflows/zizmor.yml@ff43f62eaec9f41d49b9a208d86b2eb932c97056 # v1.18.1
